version: "3.3"

services:
  backend:
    container_name: express
    ports:
      - 3000:3000
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    container_name: vite
    ports:
      - 8000:8000
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
